name: CI

on:
  push:
    branches: [1.x]
  pull_request:
    branches: [1.x]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: PHP ${{ matrix.php-versions }} | drupal ${{ matrix.drupal-version }}
    runs-on: ubuntu-24.04
    continue-on-error: false
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.4']
        drupal-version: ['10.6', '11.3', '11.4']
    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: PHPUNIT tests
        env:
          CI_IMAGE: ghcr.io/islandora/ci:${{ matrix.drupal-version }}-php${{ matrix.php-versions }}
        run: ./scripts/ci.sh
